stages:
    Data_ingestion:
      cmd : python src/shared/pipeline/pip_01_data_ingestion.py
      deps : 
        - src/shared/pipeline/pip_01_data_ingestion.py
        - Artifacts/customer_interactions.zip
        - config/config.yaml
      outs :
        - Artifacts/ingested_data

    Data_validation :
      cmd : python src/shared/pipeline/pip_02_data_validation.py
      deps :
        - src/shared/pipeline/pip_02_data_validation.py
        - Artifacts/ingested_data/
      outs :
        - Artifacts/data_validation/status.json

