stages:
  Data_ingestion:
    cmd: '" " -d Users/oviemunooboro/Product_recommendation_system/Artifacts/customer_interactions.zip
      " " -d Users/oviemunooboro/Product_recommendation_system/Artifacts/unzipped_data
      " " -o Users/oviemunooboro/Product_recommendation_system/Artifacts/ingested_data
      " " python Users/oviemunooboro/Product_recommendation_system/src/shared/pipeline/pip_01_data_ingestion.py'
