schema:
  type: StructType
  fields:
    - name: event_time
      type: TimestampType

    - name: event_type
      type: StringType
      
    - name: product_id
      type: StringType
      
    - name: category_id
      type: StringType
      
    - name: category_code
      type: StringType
      
    - name: brand
      type: StringType
      
    - name: price
      type: FloatType
      
    - name: user_id
      type: StringType
      
    - name: user_session
      type: StringType
      