

DATA_INGESTION:
    root_dir : Artifacts
    local_path : /home/azureuser/cloudfiles/code/Users/oviemunooboro/Product_recommendation_system/Artifacts/customer_interactions.zip
    target_path : Artifacts/ingested_data
    registered_name : customer_interaction_dataset

   


DATA_VALIDATION:
    root_dir : Artifacts/data_validation
    status_file: Artifacts/data_validation/status.json


DATA_TRANSFORMATION : 
    source_datapath : Artifacts/Raw_ingested_data/*.csv
    source_parquetpath : Artifacts/loaded_data.parquet

    
    





    
    